# @format

name: GitHub Classroom Workflow

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: create env file
        run: |
          echo TOKEN=${{ secrets.AUTH_TOKEN }} >> spider/.env
          echo SESSION_TOKEN=${{ secrets.SESSION_TOKEN }} >> spider/.env
      - name: install spider pkg and run
        run: |
          cd spider && npm install
          npm run start
      - name: build beta pages
        run: |
          cd web-beta && npm install
          npm run build
          npm run export
          mv out ../build
      - name: build pages
        run: |
          cd web && npm install
          npm run build
          cp dist ../build/older_version -r
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}