# @format

name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: create env file
        run: |
          echo TOKEN=${{ secrets.AUTH_TOKEN }} >> spider/.env
          echo SESSION_TOKEN=${{ secrets.SESSION_TOKEN }} >> spider/.env
      - name: add pnpm 
        run: |
          npm i pnpm -g
    
      - name: build beta pages
        run: |
          cd web-beta && pnpm install --no-frozen-lockfile
          pnpm run build
          pnpm run export
          mv out ../build
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
